In [ ]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rdkit) (2.1.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.13/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl (38.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 24.6 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.6

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem, Draw, Descriptors
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
cd drive/MyDrive/Colab Notebooks/2609_FluorescentClassification/data

/content/drive/MyDrive/Colab Notebooks/2609_FluorescentClassification/data

In [ ]:
# pandas print option
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 200)

In [ ]:
# Canonical SMILES Function
def to_canonical(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return Chem.MolToSmiles(mol, canonical=True)
    else:
        return None

In [ ]:
# Non-Fluorescent
df_N = pd.read_csv('nonfluorescent.csv', encoding='utf-8-sig')

df_N['SMILES'] = df_N['SMILES'].apply(to_canonical)
df_N = df_N.drop_duplicates(subset='SMILES', keep='first')
df_N = df_N.reset_index(drop=True)

display(df_N)

                                                                                                              SMILES
0               Nc1c(/N=N/c2ccc([N+](=O)[O-])cc2)c(S(=O)(=O)[O][Na])cc2c1C(=O)/C(=N\Nc1ccccc1)C(S(=O)(=O)[O][Na])=C2
1               Nc1c(/N=N/c2ccc(S(=O)(=O)[O][Na])cc2)cc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1ccc([N+](=O)[O-])cc1)C=C2
2                       Nc1c(/N=N/c2ccc(S(=O)(=O)[O][Na])cc2)cc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1cccc3ccccc13)C=C2
3                                            O=[N+]([O-])c1ccc2c(/N=N/c3c(O)ccc4ccccc34)c(O)cc(S(=O)(=O)[O][Na])c2c1
4     Nc1ccc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1ccc(/N=N/c3ccc(S(=O)(=O)[O][Na])cc3)c3ccccc13)C(S(=O)(=O)[O][Na])=C2
...                                                                                                              ...
2549                                                        O=C(Nc1ccc(NC(=O)c2ccccc2)c2c1C(=O)c1ccccc1C2=O)c1ccccc1
2550             Nc1nc(-c2ccc(NC(=O)c3ccccc3)c3c2C(=O)c2ccccc2C3=O)nc(-c2ccc(NC(=O)c3ccccc3)c3c2C(=O)c2ccccc2C3=O)n1
2551                                                                      O=C1/C(=c2/c(=O)c3cccc4cccc2c43)Sc2ccccc21
2552                                                                     O=C1/C(=C2\Sc3cc(Cl)ccc3C2=O)Sc2cc(Cl)ccc21
2553                            O=C1c2ccc(Nc3cccc4c3C(=O)c3ccccc3C4=O)cc2C(=O)c2ccc(Nc3cccc4c3C(=O)c3ccccc3C4=O)cc21

[2554 rows x 1 columns]

In [ ]:
# Fluorescent
df_F = pd.read_csv('fluorescent.csv', encoding='utf-8-sig')

df_F['SMILES'] = df_F['SMILES'].apply(to_canonical)
df_F = df_F.drop_duplicates(subset='SMILES', keep='first')
df_F = df_F.reset_index(drop=True)

display(df_F)

                                                  SMILES
0                    COC(=O)c1ccn2cc(-c3ccc(OC)cc3)nc2c1
1                 COC(=O)c1ccn2c(N)c(-c3ccc(OC)cc3)nc2c1
2         COC(=O)c1ccn2c(NC3CCCCC3)c(-c3ccc(OC)cc3)nc2c1
3         COC(=O)c1cccc2nc(-c3ccc(OC)cc3)c(NC3CCCCC3)n12
4                    COc1ccc(-c2nc3ncccn3c2NC2CCCCC2)cc1
...                                                  ...
2907               CN(C)c1ccc(-c2ccc3c(=O)c(O)coc3c2)cc1
2908                COc1coc2cc(-c3ccc(N(C)C)cc3)ccc2c1=O
2909            COC(=O)CN1C(=O)c2cc3ccc(N(C)C)cc3cc2C1=O
2910            CCN(CC)c1ccc2c(c1)C(C)(C)c1cc(C=O)ccc1-2
2911  CCCCCCCCC(=O)c1ccc2c(c1)C(C)(C)c1cc(N(CC)CC)ccc1-2

[2912 rows x 1 columns]

In [ ]:
# Non-Fluorescent Class Labelling
df_ndye_selected = df_N[['SMILES']].copy()
df_ndye_selected['Class'] = 0
# df_ndye_selected['Class'] = 'Non-Fluorescent'
# display(df_ndye_selected)

# Fluorescent Class Labelling
df_fdye_selected = df_F[['SMILES']].copy()
df_fdye_selected['Class'] = 1
# df_fdye_selected['Class'] = 'Fluorescent'
# display(df_fdye_selected)

# Total Dataset
df = pd.concat([df_ndye_selected, df_fdye_selected], ignore_index=True)

# 결과 확인
print(f"Total Data: {len(df)}")
print("Shape:", df.shape)
display(df)

Total Data: 5466
Shape: (5466, 2)

                                                                                                              SMILES  Class
0               Nc1c(/N=N/c2ccc([N+](=O)[O-])cc2)c(S(=O)(=O)[O][Na])cc2c1C(=O)/C(=N\Nc1ccccc1)C(S(=O)(=O)[O][Na])=C2      0
1               Nc1c(/N=N/c2ccc(S(=O)(=O)[O][Na])cc2)cc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1ccc([N+](=O)[O-])cc1)C=C2      0
2                       Nc1c(/N=N/c2ccc(S(=O)(=O)[O][Na])cc2)cc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1cccc3ccccc13)C=C2      0
3                                            O=[N+]([O-])c1ccc2c(/N=N/c3c(O)ccc4ccccc34)c(O)cc(S(=O)(=O)[O][Na])c2c1      0
4     Nc1ccc(S(=O)(=O)[O][Na])c2c1C(=O)/C(=N\Nc1ccc(/N=N/c3ccc(S(=O)(=O)[O][Na])cc3)c3ccccc13)C(S(=O)(=O)[O][Na])=C2      0
...                                                                                                              ...    ...
5461                                                                           CN(C)c1ccc(-c2ccc3c(=O)c(O)coc3c2)cc1      1
5462                                                                            COc1coc2cc(-c3ccc(N(C)C)cc3)ccc2c1=O      1
5463                                                                        COC(=O)CN1C(=O)c2cc3ccc(N(C)C)cc3cc2C1=O      1
5464                                                                        CCN(CC)c1ccc2c(c1)C(C)(C)c1cc(C=O)ccc1-2      1
5465                                                              CCCCCCCCC(=O)c1ccc2c(c1)C(C)(C)c1cc(N(CC)CC)ccc1-2      1

[5466 rows x 2 columns]

In [ ]:
df.to_csv('fluorclass_dataset.csv',index=False,encoding='utf-8-sig')